Pandas --> installer på computer (ucloud) --> import pandas til python.

In [3]:
import pandas as pd

In [8]:
a = [3, 4, 78, 6]
b = [5, 43, 79, 23]
c = [7, 18, 99, 34]

In [9]:
arla = pd.DataFrame({'a': a, 'b': b, 'c': c})

In [10]:
type(arla)

pandas.DataFrame

In [11]:
arla

    a   b   c
0   3   5   7
1   4  43  18
2  78  79  99
3   6  23  34

In [12]:
d = arla ['a']

In [13]:
type(d)

pandas.Series

In [14]:
arla["row_mean"] = arla.mean(axis=1)

In [15]:
arla

    a   b   c   row_mean
0   3   5   7   5.000000
1   4  43  18  21.666667
2  78  79  99  85.333333
3   6  23  34  21.000000

###
for at indlæse et nyt datasæt:
df = pd.read_csv('copy path på den fil der skal indsættes')

kig kapitel 4 i python bogen.

In [16]:
df = pd.read_csv('/work/CamillaSørensen#7205/experimental-/Stroop-raw-over-the-years.csv')

In [17]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year
0             4.16        6.76          4.45         4.65  2015
1             4.35        7.73          4.78         4.46  2015
2             3.60        7.00          4.00         3.50  2015
3             3.90        9.03          4.60         6.30  2015
4             4.22        9.98          6.83         6.24  2015
..             ...         ...           ...          ...   ...
200           4.77       10.00          5.66         6.24  2025
201           4.61       12.80          6.87         9.55  2025
202           4.79       10.72          5.64         7.25  2025
203           4.41        8.87          6.70         6.70  2025
204           5.50        9.80          6.20        21.70  2025

[205 rows x 5 columns]

In [18]:
df["column_mean"] = df.mean(axis=1)

In [19]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year  column_mean
0             4.16        6.76          4.45         4.65  2015      407.004
1             4.35        7.73          4.78         4.46  2015      407.264
2             3.60        7.00          4.00         3.50  2015      406.620
3             3.90        9.03          4.60         6.30  2015      407.766
4             4.22        9.98          6.83         6.24  2015      408.454
..             ...         ...           ...          ...   ...          ...
200           4.77       10.00          5.66         6.24  2025      410.334
201           4.61       12.80          6.87         9.55  2025      411.766
202           4.79       10.72          5.64         7.25  2025      410.680
203           4.41        8.87          6.70         6.70  2025      410.336
204           5.50        9.80          6.20        21.70  2025      413.640

[205 rows x 6 columns]

In [20]:
df ['meanRT'] = df.mean(axis=1)

In [21]:
df

,Reading_NoInt,Naming_Int,Naming_NoInt,Reading_Int,Year,column_mean,meanRT
0,4.16,6.76,4.45,4.65,2015,407.004,407.004
1,4.35,7.73,4.78,4.46,2015,407.264,407.264
2,3.60,7.00,4.00,3.50,2015,406.620,406.620
3,3.90,9.03,4.60,6.30,2015,407.766,407.766
4,4.22,9.98,6.83,6.24,2015,408.454,408.454
...,...,...,...,...,...,...,...
200,4.77,10.00,5.66,6.24,2025,410.334,410.334
201,4.61,12.80,6.87,9.55,2025,411.766,411.766
202,4.79,10.72,5.64,7.25,2025,410.680,410.680
203,4.41,8.87,6.70,6.70,2025,410.336,410.336
204,5.50,9.80,6.20,21.70,2025,413.640,413.640

In [25]:
df = df.drop(['Year'],axis=1)

In [26]:
df

,Reading_NoInt,Naming_Int,Naming_NoInt,Reading_Int,column_mean,meanRT
0,4.16,6.76,4.45,4.65,407.004,407.004
1,4.35,7.73,4.78,4.46,407.264,407.264
2,3.60,7.00,4.00,3.50,406.620,406.620
3,3.90,9.03,4.60,6.30,407.766,407.766
4,4.22,9.98,6.83,6.24,408.454,408.454
...,...,...,...,...,...,...
200,4.77,10.00,5.66,6.24,410.334,410.334
201,4.61,12.80,6.87,9.55,411.766,411.766
202,4.79,10.72,5.64,7.25,410.680,410.680
203,4.41,8.87,6.70,6.70,410.336,410.336
204,5.50,9.80,6.20,21.70,413.640,413.640

In [27]:
df = df.drop(['column_mean'],axis=1)

In [28]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int   meanRT
0             4.16        6.76          4.45         4.65  407.004
1             4.35        7.73          4.78         4.46  407.264
2             3.60        7.00          4.00         3.50  406.620
3             3.90        9.03          4.60         6.30  407.766
4             4.22        9.98          6.83         6.24  408.454
..             ...         ...           ...          ...      ...
200           4.77       10.00          5.66         6.24  410.334
201           4.61       12.80          6.87         9.55  411.766
202           4.79       10.72          5.64         7.25  410.680
203           4.41        8.87          6.70         6.70  410.336
204           5.50        9.80          6.20        21.70  413.640

[205 rows x 5 columns]